-- ingredient_vocab 种子词表（145 条）
--
-- 生成于 2026-08-03。设计与取舍见
-- docs/superpowers/specs/2026-08-03-ingredient-vocab-seed-design.md
--
-- 解决的问题：网页手动录食材时，词表里没有的词会被原样建成新 canonical，
-- 所以录过「番茄」之后输「西红柿」会变成两样东西，冰箱匹配就对不上了。
-- 补一份带同义词的底表，让常见食材一开始就能对上号。
--
-- 可重复执行：on conflict 走 update，跑几遍结果一样。想加词就改这个文件重跑。
--
-- ⚠️ 三条别破的约定（docs/HANDOFF.md 第三节）：
--   1. canonical 永远是中文——它是匹配和搜索的机器键
--   2. staple=true 的在冰箱匹配时默认「你有」。标多了匹配失去意义，
--      标少了每道菜都提示缺一堆
--   3. 同一个词不能同时是两个 canonical 的键，否则 buildAliasMap 静默覆盖

insert into public.ingredient_vocab (canonical, aliases, staple) values
  ('盐', array['食盐', 'salt']::text[], true),
  ('糖', array['白糖', '砂糖', '细砂糖', '白砂糖', 'sugar', 'caster sugar']::text[], true),
  ('红糖', array['黄糖', 'brown sugar']::text[], false),
  ('糖粉', array['icing sugar', 'powdered sugar']::text[], false),
  ('生抽', array['酱油', 'light soy sauce', 'soy sauce']::text[], true),
  ('老抽', array['dark soy sauce']::text[], true),
  ('蚝油', array['oyster sauce']::text[], true),
  ('香醋', array['醋', '陈醋', 'vinegar', 'black vinegar']::text[], true),
  ('白醋', array['white vinegar']::text[], false),
  ('料酒', array['黄酒', '绍兴酒', 'shaoxing wine', 'cooking wine']::text[], true),
  ('芝麻油', array['香油', '麻油', 'sesame oil']::text[], true),
  ('食用油', array['菜籽油', '植物油', '油', '芥花油', 'canola oil', 'vegetable oil']::text[], true),
  ('橄榄油', array['olive oil']::text[], true),
  ('黄油', array['butter']::text[], true),
  ('黑胡椒', array['黑胡椒粉', 'black pepper']::text[], true),
  ('白胡椒粉', array['白胡椒', 'white pepper']::text[], true),
  ('辣椒粉', array['chilli powder', 'chili powder', 'paprika']::text[], false),
  ('干辣椒', array['辣椒干', 'dried chilli', 'dried chili']::text[], false),
  ('花椒', array['sichuan pepper', 'szechuan pepper']::text[], false),
  ('八角', array['大料', 'star anise']::text[], false),
  ('桂皮', array['肉桂', 'cinnamon']::text[], false),
  ('香叶', array['月桂叶', 'bay leaf']::text[], false),
  ('孜然', array['cumin']::text[], false),
  ('咖喱粉', array['curry powder']::text[], false),
  ('五香粉', array['five spice']::text[], false),
  ('豆瓣酱', array['郫县豆瓣', 'doubanjiang', 'chilli bean paste']::text[], false),
  ('番茄酱', array['ketchup', 'tomato sauce']::text[], false),
  ('番茄膏', array['番茄酱膏', 'tomato paste']::text[], false),
  ('蜂蜜', array['honey']::text[], false),
  ('枫糖浆', array['maple syrup']::text[], false),
  ('鱼露', array['fish sauce']::text[], false),
  ('芥末', array['mustard', 'dijon mustard']::text[], false),
  ('蛋黄酱', array['美乃滋', 'mayonnaise', 'mayo']::text[], false),
  ('黑蒜酱', array['black garlic sauce']::text[], false),
  ('鸡精', array['味精', 'chicken powder', 'msg']::text[], false),
  ('高汤', array['鸡汤', '骨汤', 'stock', 'broth']::text[], false),
  ('香草精', array['vanilla extract', 'vanilla']::text[], false),
  ('酵母', array['yeast']::text[], false),
  ('可可粉', array['cocoa powder']::text[], false),
  ('淀粉', array['玉米淀粉', '生粉', '土豆淀粉', 'cornstarch', 'corn flour']::text[], true),
  ('泡打粉', array['baking powder']::text[], true),
  ('苏打粉', array['小苏打', 'baking soda', 'bicarb soda']::text[], true),
  ('姜', array['生姜', 'ginger']::text[], true),
  ('蒜', array['大蒜', '蒜瓣', 'garlic']::text[], true),
  ('葱', array['小葱', '大葱', '香葱', 'scallion', 'spring onion', 'green onion']::text[], true),
  ('洋葱', array['onion']::text[], false),
  ('香菜', array['芫荽', 'coriander', 'cilantro']::text[], false),
  ('罗勒', array['九层塔', 'basil']::text[], false),
  ('欧芹', array['parsley']::text[], false),
  ('迷迭香', array['rosemary']::text[], false),
  ('百里香', array['thyme']::text[], false),
  ('番茄', array['西红柿', 'tomato', 'tomatoes']::text[], false),
  ('土豆', array['马铃薯', '洋芋', 'potato', 'potatoes']::text[], false),
  ('胡萝卜', array['红萝卜', 'carrot', 'carrots']::text[], false),
  ('白萝卜', array['萝卜', 'daikon', 'radish']::text[], false),
  ('黄瓜', array['青瓜', 'cucumber']::text[], false),
  ('茄子', array['eggplant', 'aubergine']::text[], false),
  ('青椒', array['尖椒', 'green pepper']::text[], false),
  ('彩椒', array['甜椒', '灯笼椒', 'bell pepper', 'capsicum']::text[], false),
  ('辣椒', array['小米辣', 'chilli', 'chili']::text[], false),
  ('西兰花', array['西蓝花', '绿花菜', 'broccoli']::text[], false),
  ('花椰菜', array['菜花', '白花菜', 'cauliflower']::text[], false),
  ('卷心菜', array['圆白菜', '包菜', '甘蓝', 'cabbage']::text[], false),
  ('大白菜', array['白菜', 'napa cabbage', 'wombok']::text[], false),
  ('小白菜', array['青菜', '上海青', 'bok choy', 'pak choi']::text[], false),
  ('菠菜', array['spinach']::text[], false),
  ('生菜', array['lettuce']::text[], false),
  ('芹菜', array['celery']::text[], false),
  ('韭菜', array['chinese chives', 'garlic chives']::text[], false),
  ('豆芽', array['绿豆芽', 'bean sprouts']::text[], false),
  ('蘑菇', array['白蘑菇', '口蘑', 'mushroom', 'mushrooms']::text[], false),
  ('香菇', array['冬菇', 'shiitake']::text[], false),
  ('金针菇', array['enoki']::text[], false),
  ('木耳', array['黑木耳', 'wood ear']::text[], false),
  ('南瓜', array['pumpkin']::text[], false),
  ('冬瓜', array['winter melon']::text[], false),
  ('丝瓜', array['loofah', 'luffa']::text[], false),
  ('苦瓜', array['凉瓜', 'bitter melon']::text[], false),
  ('玉米', array['粟米', 'corn', 'sweetcorn']::text[], false),
  ('豌豆', array['青豆', 'peas']::text[], false),
  ('四季豆', array['豆角', '青豆角', 'green beans']::text[], false),
  ('芦笋', array['asparagus']::text[], false),
  ('秋葵', array['okra']::text[], false),
  ('莲藕', array['藕', 'lotus root']::text[], false),
  ('山药', array['淮山', 'yam']::text[], false),
  ('红薯', array['地瓜', '番薯', 'sweet potato']::text[], false),
  ('西葫芦', array['zucchini', 'courgette']::text[], false),
  ('牛油果', array['鳄梨', 'avocado']::text[], false),
  ('猪肉', array['pork']::text[], false),
  ('五花肉', array['pork belly']::text[], false),
  ('排骨', array['pork ribs', 'ribs']::text[], false),
  ('牛肉', array['beef']::text[], false),
  ('牛排', array['steak']::text[], false),
  ('牛肉末', array['牛肉馅', 'beef mince', 'ground beef']::text[], false),
  ('猪肉末', array['猪肉馅', '肉末', 'pork mince', 'ground pork']::text[], false),
  ('鸡肉', array['chicken']::text[], false),
  ('鸡胸肉', array['鸡胸', 'chicken breast']::text[], false),
  ('鸡腿', array['鸡腿肉', 'chicken thigh', 'drumstick']::text[], false),
  ('鸡翅', array['chicken wings']::text[], false),
  ('羊肉', array['lamb', 'mutton']::text[], false),
  ('培根', array['bacon']::text[], false),
  ('香肠', array['sausage']::text[], false),
  ('火腿', array['ham']::text[], false),
  ('鸡蛋', array['egg', 'eggs', '蛋']::text[], false),
  ('虾', array['虾仁', '大虾', 'prawn', 'prawns', 'shrimp']::text[], false),
  ('三文鱼', array['salmon']::text[], false),
  ('金枪鱼', array['吞拿鱼', 'tuna']::text[], false),
  ('沙丁鱼', array['sardine', 'sardines']::text[], false),
  ('鱿鱼', array['squid', 'calamari']::text[], false),
  ('豆腐', array['tofu']::text[], false),
  ('牛奶', array['milk', '全脂牛奶']::text[], false),
  ('酪乳', array['buttermilk', '白脱牛奶']::text[], false),
  ('酸奶', array['优格', 'yoghurt', 'yogurt']::text[], false),
  ('希腊酸奶', array['greek yoghurt', 'greek yogurt']::text[], false),
  ('淡奶油', array['鲜奶油', '稀奶油', 'cream', 'thickened cream']::text[], false),
  ('芝士', array['奶酪', '起司', 'cheese']::text[], false),
  ('马苏里拉', array['mozzarella']::text[], false),
  ('帕尔马干酪', array['帕玛森', 'parmesan']::text[], false),
  ('奶油奶酪', array['cream cheese']::text[], false),
  ('布拉塔', array['burrata']::text[], false),
  ('椰奶', array['椰浆', 'coconut milk']::text[], false),
  ('米', array['大米', '白米', '米饭', 'rice']::text[], true),
  ('面粉', array['中筋面粉', 'plain flour', 'flour', 'all purpose flour']::text[], true),
  ('全麦面粉', array['全麦粉', 'whole wheat flour', 'wholemeal flour']::text[], false),
  ('高筋面粉', array['面包粉', 'bread flour']::text[], false),
  ('燕麦片', array['老式燕麦片', '燕麦', 'oats', 'rolled oats']::text[], false),
  ('面条', array['挂面', '面', 'noodles']::text[], false),
  ('意面', array['意大利面', 'pasta', 'spaghetti']::text[], false),
  ('面包', array['吐司', 'bread', 'toast']::text[], false),
  ('米粉', array['河粉', 'rice noodles']::text[], false),
  ('芝麻', array['白芝麻', 'sesame seeds']::text[], false),
  ('花生', array['peanut', 'peanuts']::text[], false),
  ('核桃', array['walnut', 'walnuts']::text[], false),
  ('杏仁', array['almond', 'almonds']::text[], false),
  ('腰果', array['cashew', 'cashews']::text[], false),
  ('葡萄干', array['raisins']::text[], false),
  ('柠檬', array['lemon']::text[], false),
  ('青柠', array['lime']::text[], false),
  ('苹果', array['apple', 'apples']::text[], false),
  ('香蕉', array['banana', 'bananas']::text[], false),
  ('蓝莓', array['blueberry', 'blueberries']::text[], false),
  ('草莓', array['strawberry', 'strawberries']::text[], false),
  ('菠萝', array['凤梨', 'pineapple']::text[], false),
  ('橙子', array['橘子', '柳丁', 'orange']::text[], false),
  ('巧克力', array['黑巧克力', 'chocolate', 'dark chocolate']::text[], false)
on conflict (canonical) do update
  set aliases = excluded.aliases,
      staple  = excluded.staple;
